### ISSUE TITLE
404 with Docker Container since newest release

### ISSUE THREAD

**Issue by MajorTwip** [bastienwirtz/homer#441]
Docker Container not working anymore.
Will investigate and update issue

b4bz/homer from docker Hub

**Comment by Roundaround** [comment]
Is this using the `latest` tag (which is the default for no tag provided)?

**Comment by danielwerner86** [comment]
Having the same issue. When I check the network settings the NAT isn't working, it won't take an internal IP.

**Comment by Write** [comment]
Issue with latest release too
```

No configuration found, installing default config & assets
Assets directory not writable. Check assets directory permissions & docker user or skip default assets install by setting the INIT_ASSETS env var to 0
No configuration found, installing default config & assets
Assets directory not writable. Check assets directory permissions & docker user or skip default assets install by setting the INIT_ASSETS env var to 0
```

**Comment by Roundaround** [comment]
Yup this is a result of the recent Dockerfile rework. If you are using UID and GID in your docker run/docker compose, remove them now and everything should work again. See https://github.com/bastienwirtz/homer/issues/325#issuecomment-1114019406

**Comment by Write** [comment]
Indeed work perfectly, thanks.

**Comment by adyanth** [comment]
Did the location for `config.yml` also change? I had it mounted on `/www/config.yml` which no longer works. Changing it to `/www/assets/config.yml` works fine.

**Comment by Write** [comment]
hmm Mine always were been mounted to /www/assets

**Comment by Marlig76** [comment]
I think the problem is due to the change from GID/UID 911 to 1000, causing the app to not find the assets folder anymore and at the same time not being able to copy over the default assets folder. 

Solution that worked for me: 
`sudo chown -R 1000:1000 assets/`

Latest image works now again. :-)

**Comment by bastienwirtz** [comment]
Sorry for the breaking change folks :( 
As already mentioned, updating your user / permissions should fix it. For example If you used the UID / GID env var: 

Remove your UID / GID configuration
```
environment:
  - UID=1001
  - GID=1001
```
and use the `user` docker property instead
```
user: 1001:1001
```

@adyanth the config file mouved a while ago but the old path was still supported until the last release.

**Comment by auanasgheps** [comment]
I have the same issue, thanks for reporting and providing the solution.

A notice in the changelog or somewhere else would have been appreciated :)

**Comment by simonporte** [comment]
Hello,
The UID/GID change is indeed breaking and can be fixed with a change of IDs either in docker config on on filesystem via `chown` like previously said.
The container does not fix the permissions by itself.

I notice an anomaly:

When running the container, 

```
homer    | No configuration found, installing default config & assets
homer    | Starting webserver
homer    | 2022-05-01 11:09:11: (server.c.1568) server started (lighttpd/1.4.64)
```

The first line shows `No configuration found, installing default config & assets` which is wrong, the page loads correctly.
If I set this in the `docker-compose.yml` the line disappear:

```
    environment:
      - INIT_ASSETS=0
```

**Comment by Neeham** [comment]
Unfortunately, changing UID/GID to user did not fix on my end

![image](https://user-images.githubusercontent.com/10670820/166152151-d8fc4350-ec19-4e77-9151-95de16678a3d.png)

**Comment by bastienwirtz** [comment]
@simonporte Hum, that's weird, I'll look into it asap. Thanks reporting that. 

@Neeham Is the config.yml file readable by the configured `user`? Can you tell more about your setup?

**Comment by Neeham** [comment]
I delete the whole volume and all associated file with Homer to have a "fresh" start.

Grabbed: https://github.com/bastienwirtz/homer/blob/main/docker-compose.yml

Exactly the way it is. (Just updated my volume path). Same issue, went under the mapped volume path but nothing was found to be there? the /www/assets/* was empty.

Using Portainer to deploy containers. I am suspecting it's probably the user not having proper permission. Will check out when I reach home 😄

**Comment by bastienwirtz** [comment]
@Neeham ok, make sure the mounted directory is owned by the user / group 1000 **OR** change the user directive to match the owner of the mounted dir, and you should be fine.

**Comment by Gronda74** [comment]
A newb here. I was happily running the previous container in Docker on my Synology DS. Updated to the new version and I think I have hit this same permissions issue. I've removed the old UID and GID entries from the environment tab but am lost with how to:

> and use the `user` docker property instead
> 
> ```
> user: 1001:1001
> ```

I've tried adding this to the environment with USER as the variable and 1001:1001 as the Value but that doesn't seem to work. In the log for the container I keep getting the same error of "Assets directory not writable. Check assets directory permissions & docker user or skip default assets install by setting the INIT_ASSETS env var to 0".

As far as I know I don't have a user of 1001 but when I set this to 1029 which is the code for my user with admin rights it still doesn't work.

**Comment by bastienwirtz** [comment]
Hey @Gronda74, 

The `user` setting is not an environment variable, it's a docker option, in a compose file, it looks like this: https://github.com/bastienwirtz/homer/blob/main/docker-compose.yml#L13 or `--user` with the `docker run` command.

**Comment by Gronda74** [comment]
Thanks @bastienwirtz, that's what I feared you'd say. I don't have any experience of compose files. I've only got to the stage of downloading containers, entering the relevant settings and running it. So far that's been enough for my needs (and I was happy enough leaving my days of faffing around with command line wiffle back in the 90's!).

**Comment by bastienwirtz** [comment]
@Gronda74 I see, I looked quickly into [synology doc](https://kb.synology.com/en-nz/DSM/help/Docker/docker_container?version=6), I don't see how to set the user, BUT, you should be able to change the assets directory permission to 1000:1000 to make the container work.

**Comment by Gronda74** [comment]
@bastienwirtz  thanks, I’ll see if I can give that a go.

**Comment by FM-500** [comment]
> @bastienwirtz thanks, I’ll see if I can give that a go.

If that is an issue for yiu, you might want to look into using portainer.
There, you can set the user through GUI:
<img width="1700" alt="Bildschirmfoto 2022-05-03 um 16 13 00" src="https://user-images.githubusercontent.com/40071240/166470189-aa1ba6bd-3e2f-43bc-be1b-87f8442c517b.png">

**Comment by MajorTwip** [comment]
chown -R 1001:1001 . did the trick

**Comment by VajraCool** [comment]
> Sorry for the breaking change folks :( As already mentioned, updating your user / permissions should fix it. For example If you used the UID / GID env var:
> 
> Remove your UID / GID configuration
> 
> ```
> environment:
>   - UID=1001
>   - GID=1001
> ```
> 
> and use the `user` docker property instead
> 
> ```
> user: 1001:1001
> ```
> 
> @adyanth the config file mouved a while ago but the old path was still supported until the last release.

I am facing the issue as mentioned below.  I have tried removing the container and even removed image as well and tried to run

here is my `docker-compose` file 

```
# cat docker-compose.yml
---
version: "2"
services:
   homer:
     image: b4bz/homer
     container_name: homer
     volumes:
       - ./assets/:/www/assets
     ports:
       - 89:8080
#below lines are commented based on github
#https://github.com/bastienwirtz/homer/issues/325#issuecomment-1114019406
#https://github.com/bastienwirtz/homer/issues/441#issuecomment-1114170968
    #  environment:
    #    - UID=1000
    #    - GID=1000
     user: 1001:1001
     restart: unless-stopped

```
error I see

```
No configuration found, installing default config & assets

Assets directory not writable. Check assets directory permissions & docker user or skip default assets install by setting the INIT_ASSETS env var to 0
```
I see the permissions are there to write
```
# ls -ltr
total 8
drwxr-xr-x 2 root root 4096 May 31 04:07 assets
-rw-r--r-- 1 root root  244 May 31 04:10 docker-compose.yml
# whoami
root

```
I am not sure what exactly this gonna do `skip default assets install by setting the INIT_ASSETS env var to 0` ? 

is there something I am missing ?

**Comment by bastienwirtz** [comment]
@VajraCool your assets directory is owned by root, you can try `chown -R 1001:1001 </your/assets/dir>`.

**Comment by Neeham** [comment]
Since a few are still struggling. Those on Qnap. I used:

`user: 911:911`

and it worked flawlessly :)

**Comment by PigeonFX** [comment]
> > @bastienwirtz thanks, I’ll see if I can give that a go.
> 
> If that is an issue for yiu, you might want to look into using portainer. There, you can set the user through GUI: <img alt="Bildschirmfoto 2022-05-03 um 16 13 00" width="1700" src="https://user-images.githubusercontent.com/40071240/166470189-aa1ba6bd-3e2f-43bc-be1b-87f8442c517b.png">

Any chance you can talk me through this, super noob using portainer for the first time and getting the [404] and the error:
```
Assets directory not writable. Check assets directory permissions & docker user or skip default assets install by setting the INIT_ASSETS env var to 0
No configuration found, installing default config & assets
```
